# collection.py

SHARK_COLLECTION = {
    "calm": {
        "title": "고래상어",
        "species": "Whale Shark",
        "mood": "Calm",
        "emoji": "🐋",
        "summary": "거대한 몸집으로도 잔잔하게 바다를 유영하는 고래상어처럼, calm은 조용하고 안정적인 흐름을 닮았습니다.",
        "color": "#38bdf8",
        "habitat": "따뜻한 열대·아열대 바다",
        "personality": "느긋함, 안정감, 넓은 품",
        "keywords": ["평온", "안정", "천천히", "회복"],
        "description": "고래상어는 현존하는 가장 큰 어류로, 거대한 입으로 플랑크톤과 작은 생물을 걸러 먹습니다.",
    },
    "calm_2": {
        "title": "제브라상어",
        "species": "Zebra Shark",
        "mood": "Calm",
        "emoji": "🦓",
        "summary": "산호초 위에서 느긋하게 쉬는 제브라상어처럼, 지금은 가만히 머물러도 괜찮아요.",
        "color": "#67e8f9",
        "habitat": "인도-태평양 산호초",
        "personality": "온순함, 여유, 평화",
        "keywords": ["여유", "쉼", "산호", "고요"],
        "description": "제브라상어는 어릴 때 줄무늬가 있다가 성장하면 점무늬로 변하는 독특한 상어입니다.",
    },
    "calm_3": {
        "title": "엔젤상어",
        "species": "Angel Shark",
        "mood": "Calm",
        "emoji": "👼",
        "summary": "모래 바닥에 납작하게 엎드려 쉬는 엔젤상어처럼, 조용히 내려놓는 시간도 필요해요.",
        "color": "#a5f3fc",
        "habitat": "온대 해저 모래밭",
        "personality": "인내, 정적, 기다림",
        "keywords": ["고요", "바닥", "인내", "평화"],
        "description": "엔젤상어는 납작한 몸으로 해저에 숨어 먹이를 기다리는 매복형 포식자입니다.",
    },
    "happy": {
        "title": "레오파드상어",
        "species": "Leopard Shark",
        "mood": "Happy",
        "emoji": "🐆",
        "summary": "밝은 무늬와 부드러운 움직임을 가진 레오파드상어처럼, happy는 가볍고 생기 있는 기분을 닮았습니다.",
        "color": "#5eead4",
        "habitat": "얕은 연안과 모래 바닥",
        "personality": "밝음, 경쾌함, 친근함",
        "keywords": ["기쁨", "가벼움", "생기", "미소"],
        "description": "레오파드상어는 몸의 표범무늬 같은 반점 때문에 이름이 붙었고, 얕은 연안에서 자주 발견됩니다.",
    },
    "happy_2": {
        "title": "블루상어",
        "species": "Blue Shark",
        "mood": "Happy",
        "emoji": "💙",
        "summary": "맑은 바다를 자유롭게 누비는 블루상어처럼, 오늘의 기분은 탁 트인 하늘 같아요.",
        "color": "#22d3ee",
        "habitat": "전 세계 외해",
        "personality": "자유로움, 활발함, 호기심",
        "keywords": ["자유", "활발", "맑음", "기분좋음"],
        "description": "블루상어는 아름다운 남색 등과 흰 배를 가진 우아한 원양성 상어입니다.",
    },
    "happy_3": {
        "title": "포트잭슨상어",
        "species": "Port Jackson Shark",
        "mood": "Happy",
        "emoji": "😊",
        "summary": "둥글고 귀여운 얼굴의 포트잭슨상어처럼, 소소한 행복이 얼굴에 번져요.",
        "color": "#2dd4bf",
        "habitat": "호주 남부 연안",
        "personality": "귀여움, 소박함, 만족",
        "keywords": ["만족", "소소함", "귀여움", "웃음"],
        "description": "포트잭슨상어는 독특한 이마 무늬와 뭉툭한 주둥이로 유명한 호주 토착 상어입니다.",
    },
    "angry": {
        "title": "백상아리",
        "species": "Great White Shark",
        "mood": "Angry",
        "emoji": "🦷",
        "summary": "강한 존재감과 날카로운 추진력을 가진 백상아리처럼, angry는 방향을 잡으면 힘이 되는 강한 에너지입니다.",
        "color": "#f87171",
        "habitat": "온대 연안과 외해",
        "personality": "강렬함, 직진성, 압도감",
        "keywords": ["분노", "추진력", "강함", "폭발"],
        "description": "백상아리는 뛰어난 후각을 가지고 있으며, 물속의 아주 미세한 냄새도 감지할 수 있습니다.",
    },
    "angry_2": {
        "title": "황소상어",
        "species": "Bull Shark",
        "mood": "Angry",
        "emoji": "🐂",
        "summary": "거침없이 돌진하는 황소상어처럼, 지금의 에너지는 강하지만 방향을 잡으면 힘이 돼요.",
        "color": "#ef4444",
        "habitat": "연안, 강, 하구",
        "personality": "공격성, 돌진, 거침없음",
        "keywords": ["돌진", "거침", "강렬", "억울"],
        "description": "황소상어는 민물에서도 생존할 수 있는 드문 상어로, 강한 턱 힘을 가지고 있습니다.",
    },
    "angry_3": {
        "title": "타이거상어",
        "species": "Tiger Shark",
        "mood": "Angry",
        "emoji": "🐯",
        "summary": "어둠 속에서 줄무늬를 드러내는 타이거상어처럼, 분노도 하나의 무늬가 될 수 있어요.",
        "color": "#dc2626",
        "habitat": "열대·아열대 연안",
        "personality": "위압감, 대담함, 존재감",
        "keywords": ["위압", "대담", "어둠", "폭풍"],
        "description": "타이거상어는 잡식성으로 유명하며, 몸의 호랑이 줄무늬가 성장하면서 희미해집니다.",
    },
    "sad": {
        "title": "그린란드상어",
        "species": "Greenland Shark",
        "mood": "Sad",
        "emoji": "🧊",
        "summary": "깊고 차가운 바다를 천천히 지나는 그린란드상어처럼, sad는 조용히 가라앉은 마음의 깊이를 닮았습니다.",
        "color": "#818cf8",
        "habitat": "북극권과 깊은 차가운 바다",
        "personality": "깊이감, 고요함, 느린 회복",
        "keywords": ["우울", "고요", "심해", "가라앉음"],
        "description": "그린란드상어는 매우 오래 사는 상어로 알려져 있으며, 수백 년까지 생존할 수 있다고 추정됩니다.",
    },
    "sad_2": {
        "title": "고블린상어",
        "species": "Goblin Shark",
        "mood": "Sad",
        "emoji": "👻",
        "summary": "깊은 심해에서 홀로 떠도는 고블린상어처럼, 외로운 시간도 결국 지나가요.",
        "color": "#a78bfa",
        "habitat": "심해 200m 이하",
        "personality": "고독, 미스터리, 깊이",
        "keywords": ["외로움", "심해", "고독", "어둠"],
        "description": "고블린상어는 '살아있는 화석'으로 불리며, 긴 주둥이와 돌출되는 턱이 특징입니다.",
    },
    "sad_3": {
        "title": "바스킹상어",
        "species": "Basking Shark",
        "mood": "Sad",
        "emoji": "🌊",
        "summary": "거대한 입을 벌리고 천천히 떠다니는 바스킹상어처럼, 슬픔도 흘러가게 두면 괜찮아요.",
        "color": "#6366f1",
        "habitat": "온대 외해",
        "personality": "무력감, 흘러감, 수용",
        "keywords": ["무력", "흘러감", "눈물", "수용"],
        "description": "바스킹상어는 고래상어 다음으로 큰 어류로, 입을 크게 벌려 플랑크톤을 걸러 먹습니다.",
    },
    "tired": {
        "title": "너스상어",
        "species": "Nurse Shark",
        "mood": "Tired",
        "emoji": "💤",
        "summary": "바닥 가까이 머물며 에너지를 아끼는 너스상어처럼, tired는 쉬어가야 할 몸과 마음의 신호입니다.",
        "color": "#cbd5e1",
        "habitat": "따뜻한 얕은 바다와 산호초 근처",
        "personality": "휴식, 저속, 회복",
        "keywords": ["피로", "쉼", "회복", "느림"],
        "description": "너스상어는 낮에는 바닥이나 틈 사이에서 쉬고, 주로 밤에 먹이를 찾는 습성이 있습니다.",
    },
    "tired_2": {
        "title": "우바잉상어",
        "species": "Wobbegong Shark",
        "mood": "Tired",
        "emoji": "🛌",
        "summary": "바닥에 납작 엎드려 꼼짝 않는 우바잉상어처럼, 지금은 움직이지 않아도 돼요.",
        "color": "#94a3b8",
        "habitat": "호주·인도네시아 해저",
        "personality": "정지, 위장, 에너지 절약",
        "keywords": ["정지", "바닥", "무기력", "쉼"],
        "description": "우바잉상어는 카펫상어라고도 불리며, 해저에 완벽히 위장하여 먹이를 기다립니다.",
    },
    "tired_3": {
        "title": "쿠키커터상어",
        "species": "Cookiecutter Shark",
        "mood": "Tired",
        "emoji": "🍪",
        "summary": "작은 몸으로 깊은 바다를 오가는 쿠키커터상어처럼, 작은 에너지로도 하루를 버텨낸 당신은 대단해요.",
        "color": "#64748b",
        "habitat": "심해 (낮), 표층 (밤)",
        "personality": "소모, 반복, 작은 힘",
        "keywords": ["소모", "번아웃", "반복", "지침"],
        "description": "쿠키커터상어는 큰 동물의 몸에서 동그란 살점을 떼어먹는 독특한 기생형 포식자입니다.",
    },
    "anxious": {
        "title": "귀상어",
        "species": "Hammerhead Shark",
        "mood": "Anxious",
        "emoji": "🔨",
        "summary": "넓은 머리로 주변을 예민하게 살피는 귀상어처럼, anxious는 많은 것을 동시에 감지하는 마음과 닮았습니다.",
        "color": "#c084fc",
        "habitat": "열대·온대 바다",
        "personality": "예민함, 관찰, 경계",
        "keywords": ["불안", "걱정", "긴장", "감지"],
        "description": "귀상어의 넓은 머리 구조는 시야와 감각 기관을 넓게 활용하는 데 도움을 줍니다.",
    },
    "anxious_2": {
        "title": "환도상어",
        "species": "Thresher Shark",
        "mood": "Anxious",
        "emoji": "🌀",
        "summary": "긴 꼬리를 휘두르며 경계하는 환도상어처럼, 불안은 당신이 무언가를 지키려는 신호예요.",
        "color": "#a855f7",
        "habitat": "외해와 연안",
        "personality": "경계, 민첩, 과민",
        "keywords": ["경계", "초조", "민감", "신경"],
        "description": "환도상어는 몸길이의 절반에 달하는 긴 꼬리지느러미로 먹이를 기절시킵니다.",
    },
    "anxious_3": {
        "title": "톱상어",
        "species": "Saw Shark",
        "mood": "Anxious",
        "emoji": "🪚",
        "summary": "톱 모양 주둥이로 주변을 탐지하는 톱상어처럼, 예민함은 때로 생존의 감각이에요.",
        "color": "#d946ef",
        "habitat": "온대·열대 해저",
        "personality": "탐지, 예민, 방어",
        "keywords": ["탐지", "복잡", "떨림", "방어"],
        "description": "톱상어는 톱 모양의 주둥이에 있는 전기수용기로 모래 속 먹이를 감지합니다.",
    },
    "excited": {
        "title": "청상아리",
        "species": "Mako Shark",
        "mood": "Excited",
        "emoji": "⚡",
        "summary": "빠르고 날렵하게 물살을 가르는 청상아리처럼, excited는 앞으로 튀어나가려는 에너지를 닮았습니다.",
        "color": "#facc15",
        "habitat": "외해와 따뜻한 바다",
        "personality": "속도감, 기대감, 반짝임",
        "keywords": ["설렘", "속도", "기대", "도약"],
        "description": "청상아리는 상어 중에서도 매우 빠른 종으로, 순간적으로 강한 속도를 낼 수 있습니다.",
    },
    "excited_2": {
        "title": "스피너상어",
        "species": "Spinner Shark",
        "mood": "Excited",
        "emoji": "🌟",
        "summary": "물 위로 뛰어올라 회전하는 스피너상어처럼, 지금의 설렘을 마음껏 표현해도 좋아요.",
        "color": "#fbbf24",
        "habitat": "열대·아열대 연안",
        "personality": "역동, 점프, 에너지 폭발",
        "keywords": ["흥분", "점프", "에너지", "회전"],
        "description": "스피너상어는 먹이를 쫓을 때 물 밖으로 뛰어올라 회전하는 독특한 사냥법을 씁니다.",
    },
    "excited_3": {
        "title": "환도상어(설렘)",
        "species": "Thresher Shark",
        "mood": "Excited",
        "emoji": "🔥",
        "summary": "긴 꼬리를 힘차게 휘두르며 돌진하는 환도상어처럼, 지금의 에너지는 무엇이든 해낼 수 있어요.",
        "color": "#f59e0b",
        "habitat": "외해와 연안",
        "personality": "폭발적 에너지, 전력질주, 몰입",
        "keywords": ["폭발", "몰입", "전력", "도약"],
        "description": "환도상어는 몸길이의 절반에 달하는 긴 꼬리지느러미를 채찍처럼 휘둘러 먹이를 사냥합니다.",
    },
}


def get_collection_items():
    return SHARK_COLLECTION


def get_collection_item(mood_key):
    return SHARK_COLLECTION.get(mood_key)
